import { Toaster } from "./_components/ui/sonner";
import { Footer } from "./_components/footer/footer";

import AuthProvider from "./_providers/auth";

import { Inter } from "next/font/google";
import type { Metadata } from "next";

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="pt-br" className="dark">
            <body className={inter.className}>
                <AuthProvider>
                    <div className="flex flex-col h-full">
                        <div className="flex-1">
                            {children}
                        </div>

                        <Footer />
                    </div>
                </AuthProvider>

                <Toaster />
            </body>
        </html>
    );
};