import type { Metadata } from "next";
import { Sidebar } from './_components/Sidebar';
import { Inter } from "next/font/google";
import "./globals.css";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter(
    {
        subsets: ["latin"],
        display: "auto",
    }
);

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="pt-br">
            <body className={`${inter.className} antialiased`}>
                <div className="flex h-full">
                    <Sidebar />
                    {children}
                </div>
            </body>
        </html>
    );
};